### ISSUE TITLE
COTIZAR En APROMED error al adjuntar archivo

### ISSUE THREAD

**Issue by antoniogalli** [ShinSeiki/technik_odoo_instance#14]
En el producto al adjuntar un documento antes se podía adjuntar sin problemas,hoy muestra un error 

![WhatsApp Image 2024-09-11 at 5 22 17 PM](https://github.com/user-attachments/assets/5f989568-eb77-4a42-bd12-3a1220557bff)

DESTALLE DEL ERROR

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/mnt/src-addons/src/odoo13-apromed/custom-addons/ks_list_view_manager/controllers/lvm_controller.py", line 16, in call_kw
    call_kw_result = super(LvmController, self).call_kw(model, method, args, kwargs, path)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1342, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 390, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 377, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale_timesheet/models/product.py", line 117, in write
    return super(ProductTemplate, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock_landed_costs/models/product.py", line 21, in write
    return super().write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock_account/models/product.py", line 50, in write
    res = super(ProductTemplate, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/stock/models/product.py", line 756, in write
    return super(ProductTemplate, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/product/models/product_template.py", line 411, in write
    res = super(ProductTemplate, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 323, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_activity.py", line 726, in write
    return super(MailActivityMixin, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/mixins.py", line 168, in write
    return super(WebsitePublishedMixin, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/rating/models/rating_mixin.py", line 76, in write
    result = super(RatingMixin, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3625, in write
    field.write(self, vals[fname])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2909, in write
    return self.write_batch([(records, value)])
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2930, in write_batch
    return self.write_real(records_commands_list, create)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3107, in write_real
    flush()
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3069, in flush
    comodel.create(to_create)
  File "<decorator-gen-174>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 320, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 320, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/ir_attachment.py", line 25, in create
    return super(Attachment, self).create(vals)
  File "<decorator-gen-40>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 338, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 545, in create
    return super(IrAttachment, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 339, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3825, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3897, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2287, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2299, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.attachment.type: 'product'

**Comment by antoniogalli** [comment]
Propuesta y presupuesto para el 25092024

**Comment by ShinSeiki** [comment]
Error odoo v13. se sospecha q esta caracteristica no era funcional para esta version se corrige el mapeo de la vista para poder habilitar la funcionalidad
